### ISSUE TITLE
Pillow no longer has a _makeself() method

### ISSUE THREAD

**Issue by vitorio** [hbldh/hitherdither#1]
As of Pillow 4.0.0 (2017-01-01), _makeself() was replaced by _new: https://github.com/python-pillow/Pillow/blob/master/CHANGES.rst#400-2017-01-01

> Use Image._new() instead of _makeself() #2248 [homm]

Issue: https://github.com/python-pillow/Pillow/pull/2248

Changing the two references in `palette.py` from _makeself to _new makes hitherdither work with recent Pillow releases.

**Comment by hbldh** [comment]
Corrected this for version 0.1.5 now present `master` branch. Thank you!
