### ISSUE TITLE
Cluster dot dithering isn't included in the module

### ISSUE THREAD

**Issue by vitorio** [hbldh/hitherdither#2]
There's no import statement for the cluster dot dithering module, so it's not accessible.

`ordered/__init__.py` needs `from . import cluster` added to it, which makes it accessible.

**Comment by hbldh** [comment]
Corrected this for version 0.1.5 now present `master` branch. Thank you!

The reason for not adding it in the first place was that I had not tested it at all. Have now, works with color images at least. As with most everything else in `hitherdither` it does not handle greyscale...
